%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\giuli\Dropbox (Politecnico Di Torino Studenti)\POLITO 2022_2023\Computational Linear Algebra FLSP\Spectral_clustering_CLAFLSP\data\atom.csv
%
% Auto-generated by MATLAB on 11-May-2023 12:45:48

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["id", "xAxis", "yAxis", "zAxis", "Cluster_id"];
opts.VariableTypes = ["double", "double", "double", "double", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Cluster_id", "EmptyFieldRule", "auto");

% Import the data
atom = readtable("C:\Users\giuli\Dropbox (Politecnico Di Torino Studenti)\POLITO 2022_2023\Computational Linear Algebra FLSP\Spectral_clustering_CLAFLSP\data\atom.csv", opts);


%% Clear temporary variables
clear opts

save('atom.mat', '-mat')